language: node_js
node_js:
- '7'
- '8'
- '9'
notifications:
  slack:
    secure: D+HIHc+MF10FMRsBPOvdMFcr9H9syQCSO69/C6X5Gt0gBS52OYtXrGoSIhKK/CMwe+ZPhLbx8WwbMaksMBK5sgnhRaGR/5YxeHJ1UNAMIuF6BnVNdrjtYscnyHyRWnmGsTF1nxT1RA9hr/iXmQLNrmCfRNGXANrsJ4tBHPgvtkyL6MV5GB7S6mBP9fq/u0u3Au8cx8cmYz9Plzp5P+pCeInJknN/GTsD7VQhIXa/dHFi1pNx7UGEupYP6+jFbOgJgvDNib6uqYSnVOUk1Gy9BXV/9YeJcn8hE8LYGujbhLSU7ZyijIVzeyQnO3X33jeGYeQKO6UXwS8EuE0tn4oSWlmaqIxAiuHBzqxKxH/0g2tWVN/4ITwtqUJ7U7aZWEptvQDsolKmpyUm1xYWSoTu4pEaOpMF+/SdDCUlSMd+si2mXNKBguyj6nZz4Yx5KIMjEP4gxIyt+6+pYHhpGJ/qe35xmlczKzGG4rSvwyIKOkALpUvp6PsADWpx4gvd97hz0C/AUuQEOlSxqJngucpt0BtpnD19SlY+fuzKuWXJCmAzXhnozAGIo4r2/t7DWjB8HFVg6FUPv8dKVhPdQTcRqHx+DNpWTt5gvskFGUM7m5VoGxmhHGlX9JYj/9F/mStJNwRsvvr1kBs7dQ1kumjNfghvRYPjgb0LFC37xQ+6LDE=
